### ISSUE TITLE
Fail to start droppy in a Seagate NAS OS App

### ISSUE THREAD

**Issue by Djailla** [silverwind/droppy#264]
Hello,

I'm currently porting Droppy app to Seagate NAS OS App environment and put the code on GitHub 

https://github.com/Djailla/nas-os-droppy

I'm trying to run Droppy on a Debian Wheezy Lamp x86 chroot with nodejs 6.x and classic apt-get / npm commands provided on the How-To but got this error when starting droppy

    root@TestBee:/# droppy start --filesdir /shares --configdir /opt/droppy
    /usr/lib/node_modules/droppy/node_modules/uws/uws.js:14
            throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
            ^

    Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
        at e (/usr/lib/node_modules/droppy/node_modules/uws/uws.js:14:15)
        at Object.<anonymous> (/usr/lib/node_modules/droppy/node_modules/uws/uws.js:17:3)
        at Module._compile (module.js:556:32)
        at Object.Module._extensions..js (module.js:565:10)
        at Module.load (module.js:473:32)
        at tryModuleLoad (module.js:432:12)
        at Function.Module._load (module.js:424:3)
        at Module.require (module.js:483:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/lib/node_modules/droppy/server/server.js:16:16)

Any idea on how to fix it ?

**Comment by silverwind** [comment]
Looks like a [uWebSockets](https://github.com/uWebSockets/uWebSockets) build failure. Can you show the content of `/usr/lib/node_modules/droppy/node_modules/uws/build_log.txt`?

**Comment by Djailla** [comment]
Here it is :

`gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/rainbow/.node-gyp/6.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/droppy/node_modules/uws/.node-gyp"
make: Entering directory `/usr/lib/node_modules/droppy/node_modules/uws/build'
  CXX(target) Release/obj.target/uws/src/Extensions.o
In file included from ../src/Extensions.cpp:1:0:
../src/Extensions.h: In constructor 'PerMessageDeflate::PerMessageDeflate(ExtensionsParser&, int, std::string&)':
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::msg' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::state' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zalloc' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zfree' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::opaque' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::data_type' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::adler' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::reserved' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::msg' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::state' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zalloc' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zfree' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::opaque' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::data_type' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::adler' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::reserved' [-Wmissing-field-initializers]
  CXX(target) Release/obj.target/uws/src/HTTPSocket.o
../src/HTTPSocket.cpp: In static member function 'static void uWS::HTTPSocket::onReadable(uv_poll_t*, int, int)':
../src/HTTPSocket.cpp:121:93: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  CXX(target) Release/obj.target/uws/src/Network.o
  CXX(target) Release/obj.target/uws/src/Server.o
In file included from ../src/Server.cpp:5:0:
../src/Extensions.h: In constructor 'PerMessageDeflate::PerMessageDeflate(ExtensionsParser&, int, std::string&)':
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::msg' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::state' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zalloc' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zfree' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::opaque' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::data_type' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::adler' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::reserved' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::msg' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::state' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zalloc' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zfree' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::opaque' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::data_type' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::adler' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::reserved' [-Wmissing-field-initializers]
../src/Server.cpp: In constructor 'uWS::Server::Server(uWS::EventSystem&, int, unsigned int, unsigned int, uWS::SSLContext)':
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::next_in' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::avail_in' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::total_in' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::next_out' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::avail_out' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::total_out' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::msg' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::state' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::zalloc' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::zfree' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::opaque' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::data_type' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::adler' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::reserved' [-Wmissing-field-initializers]
../src/Server.cpp: In lambda function:
../src/Server.cpp:179:44: error: 'this' was not captured for this lambda function
../src/Server.cpp: In lambda function:
../src/Server.cpp:183:46: error: 'this' was not captured for this lambda function
make: *** [Release/obj.target/uws/src/Server.o] Error 1
make: Leaving directory `/usr/lib/node_modules/droppy/node_modules/uws/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.11.0-12-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/droppy/node_modules/uws
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok`

**Comment by silverwind** [comment]
Which version of gcc are you using?

**Comment by Djailla** [comment]
root@TestBee:/# gcc --version
	gcc (Debian 4.7.2-5) 4.7.2
	Copyright (C) 2012 Free Software Foundation, Inc.
	This is free software; see the source for copying conditions.  There is NO
	warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by silverwind** [comment]
Filed https://github.com/uWebSockets/uWebSockets/issues/240. If my assumption is correct, it should build on gcc 4.8.0, if that's an option for you.

**Comment by Djailla** [comment]
Not so easy for me to update gcc, let's wait and see what happens for the ticket you opened

**Comment by silverwind** [comment]
While that issue looks dire, I thought about adding a fallback to `ws` (the slower websocket library) in case `uws` fails to build. Care to give it a try?

````
$ npm install -g https://github.com/silverwind/droppy/tarball/master
````

**Comment by Djailla** [comment]
Hello, no big success :(

	root@TestBee:/# droppy start --filesdir /shares --configdir /opt/droppy
	[INFO] `uws` module failed to build, falling back to `ws`
	           .:.        __
	    :::  .:::::.   --|  |---- ----- ----- ----- -- --
	  ..:::..  :::    |  _  |   _|  _  |  _  |  _  |  |  |
	   ':::'   :::    |_____|__| |_____|   __|   __|___  |
	     '                             |__|  |__|  |_____|

	 droppy 5.0.12 running on node 6.4.0
	 config at /opt/droppy
	 files at /shares

	2016-09-08 09:48:35 [INFO] Loading resources ...
	2016-09-08 09:48:35 [INFO] ENOENT /usr/lib/node_modules/droppy/dist/cache.json, building cache ...
	2016-09-08 09:48:35 [INFO] Loading resources done
	2016-09-08 09:48:35 [ERROR] Missing devDependencies to compile resource cache, please reinstall or run `npm install --only=dev` inside the project directory
	    at compile (/usr/lib/node_modules/droppy/server/resources.js:216:15)
	    at ReadFileContext.<anonymous> (/usr/lib/node_modules/droppy/server/resources.js:151:14)
	    at ReadFileContext.callback (/usr/lib/node_modules/droppy/node_modules/graceful-fs/graceful-fs.js:78:16)
	    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)

Even trying with :

`npm install --only=dev -g https://github.com/silverwind/droppy/tarball/master`

**Comment by Djailla** [comment]
On the other side, I'm trying to generate a new chroot with debian jessie.

**Comment by silverwind** [comment]
Ah, you're missing the `dist` files which are only published on npm. I pushed a new version, which should work:

```
npm install -g droppy@latest
```

**Comment by Djailla** [comment]
I managed to get a debian jessie and then no more issue ;)

**Comment by silverwind** [comment]
Great to hear. I managed to successfully build it on Wheezy too now, so it should be easier for you to update in the future.
